project:
  name: questionnaire_investigation_api

spring:
  application:
    name: questionnaire_investigation_api
  datasource:
    dynamic:
      primary: mysql8
      datasource:
        mysql8:
          url: jdbc:mysql://localhost:3306/questionnaire?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        sqlserver:
          url: jdbc:sqlserver://119.97.224.22:1433
          username: sa
          password: 1qa4RF7uj!%_+9ol8IK
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置

mybatis-plus:
  configuration:
    #控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #取下驼峰转下划线
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true #mybatis返回类型为map返回字段值为null的字段
  mapper-locations: classpath:mapper/*Mapper.xml
  #逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      directory: /logs/accesslog/
      enabled: true

logging:
  level:
    com:
      cn:
        hs:
          mapper: debug
  config: classpath:logback.xml