project:
  name: document_manager_api


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  profiles:
    active: dev
  application:
    name: document_manager_api
  datasource:
    dynamic:
      primary: db1
      datasource:
        db1:
          url: jdbc:mysql://localhost:3306/bmw?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        db2:
          url: jdbc:mysql://localhost:3306/bmw2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置


mybatis-plus:
  configuration:
    #控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #取下驼峰转下划线
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true #mybatis返回类型为map返回字段值为null的字段
  mapper-locations: classpath:mapper/*Mapper.xml
  #逻辑删除
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      directory: /logs/accesslog/
      enabled: true

logging:
  level:
    com:
      cn:
        hs:
          mapper: debug
  config: classpath:logback.xml

